// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxskvvholkptqyekxtdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4c2t2dmhvbGtwdHF5ZWt4dGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTYzOTYsImV4cCI6MjA2MzQzMjM5Nn0.GkD-Sdernn8-dH_gD5KawJ05Ib3aP1aDnDYQQK8u9Yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);